import React, { useState } from 'react';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { VideoList } from '../../components';
import { useQueryGetVidioList } from '../../hooks';

function UseQueryVersion() {
    // console.log(props.items);
    const { data, isLoading, isError } = useQueryGetVidioList();

    const [selectedVideo, setSelectedVideo] = useState(null);

    const selectVideo = (video: any) => {
        setSelectedVideo(video);
    };

    if (isLoading)
        return (
            <div
                style={{
                    display: 'flex',
                    justifyContent: 'center',
                    width: '100%',
                    height: '100vh',
                    paddingLeft: '1rem',
                }}
            >
                로딩중입니다...
            </div>
        );

    if (isError)
        return (
            <div
                style={{
                    display: 'flex',
                    justifyContent: 'center',
                    width: '100%',
                    height: '100vh',
                    paddingLeft: '1rem',
                }}
            >
                에러입니다...
            </div>
        );

    return (
        <div className={styles.container}>
            <Head>
                <title>useQuery페이지</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <VideoList
                videos={data.items}
                onVideoClick={selectVideo}
                display={selectedVideo ? 'list' : 'grid'}
            />
        </div>
    );
}

export default UseQueryVersion;
