import React, { useState } from 'react';

import type { GetStaticProps, GetServerSideProps, NextPage } from 'next';

import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Navbar, VideoList } from '../components';
import { axios } from '../utils';
const Home: NextPage = (props: any) => {
    console.log({ props });
    const [selectedVideo, setSelectedVideo] = useState(null);

    const selectVideo = (video: any) => {
        setSelectedVideo(video);
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>타이틀?</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <VideoList
                videos={props.items}
                onVideoClick={selectVideo}
                display={selectedVideo ? 'list' : 'grid'}
            />
        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
    const data = await axios.get(
        'https://www.googleapis.com/youtube/v3/videos?part=snippet&chart=mostPopular&maxResults=10&key=AIzaSyAtrSZkopq--QXlpEYQ5SrM9Kg5TZlZMl0',
    );

    return { props: data.data };
};

export default Home;
